import{a as P,S as q,i as s}from"./assets/vendor-DqB7j7Ix.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const i of e)if(i.type==="childList")for(const l of i.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function r(e){const i={};return e.integrity&&(i.integrity=e.integrity),e.referrerPolicy&&(i.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?i.credentials="include":e.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function a(e){if(e.ep)return;e.ep=!0;const i=r(e);fetch(e.href,i)}})();const R="51403222-4fbdc3af82d89be9b055ca0a4",M="https://pixabay.com/api/";async function L(t,o=1,r=15){return(await P.get(M,{params:{key:R,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:r}})).data}const h=document.querySelector(".gallery"),n=document.querySelector(".loader"),$=new q(".gallery a",{captionsData:"alt",captionDelay:250});function w(t,o=!1){const r=E(t);o?h.insertAdjacentHTML("beforeend",r):h.innerHTML=r,$.refresh()}function E(t){return t.map(({webformatURL:o,largeImageURL:r,tags:a,likes:e,views:i,comments:l,downloads:S})=>`
        <a class="gallery-item" href="${r}">
          <img src="${o}" alt="${a}" width="360" height="200" />
          <div class="gallery-info">
            <ul class="info-list">
              <li><h3>Likes</h3><p>${e}</p></li>
              <li><h3>Views</h3><p>${i}</p></li>
              <li><h3>Comments</h3><p>${l}</p></li>
              <li><h3>Downloads</h3><p>${S}</p></li>
            </ul>
          </div>
        </a>
      `).join("")}function B(){h.innerHTML=""}function O(){n==null||n.classList.remove("is-hidden")}function g(){n==null||n.classList.add("is-hidden")}const y=document.querySelector(".form"),p=document.querySelector(".load"),b=document.querySelector(".gallery-loader");let m="",c=1;const u=15;let d=0;y.addEventListener("submit",async t=>{t.preventDefault();const o=y.elements["search-text"].value.trim();if(!o){s.warning({title:"Warning",message:"Please enter a search term!",position:"topRight",timeout:3e3,color:"orange"});return}m=o,c=1,B(),f(),O();try{const r=await L(m,c,u);if(d=r.totalHits,g(),!r.hits.length){s.error({title:"Sorry",message:"No images found. Please try another query!",position:"topRight",timeout:5e3,color:"red"});return}w(r.hits),s.success({title:"Success",message:`Found ${d} images!`,position:"topRight",timeout:3e3,color:"green"}),d>u&&v()}catch(r){g(),s.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight",timeout:5e3,color:"red"}),console.error("Fetch error:",r)}});p.addEventListener("click",async()=>{c+=1,x(),f();try{const t=await L(m,c,u);w(t.hits,!0),D(),c*u>=d?(s.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:4e3,color:"blue"}),f()):v()}catch(t){s.error({title:"Error",message:"Could not load more images.",position:"topRight",timeout:5e3,color:"red"}),console.error("Load more error:",t)}finally{H()}});function v(){p.classList.remove("is-hidden")}function f(){p.classList.add("is-hidden")}function x(){b.classList.remove("is-hidden")}function H(){b.classList.add("is-hidden")}function D(){const t=document.querySelector(".gallery a");if(t){const o=t.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
