import{a as q,S as P,i as s}from"./assets/vendor-DqB7j7Ix.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const i of e)if(i.type==="childList")for(const l of i.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function r(e){const i={};return e.integrity&&(i.integrity=e.integrity),e.referrerPolicy&&(i.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?i.credentials="include":e.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function a(e){if(e.ep)return;e.ep=!0;const i=r(e);fetch(e.href,i)}})();const M="51403222-4fbdc3af82d89be9b055ca0a4",R="https://pixabay.com/api/";async function y(t,o=1,r=15){return(await q.get(R,{params:{key:M,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:r}})).data}const h=document.querySelector(".gallery"),n=document.querySelector(".loader"),L=document.querySelector(".load"),w=document.querySelector(".gallery-loader"),$=new P(".gallery a",{captionsData:"alt",captionDelay:250});function b(t,o=!1){const r=B(t);o?h.insertAdjacentHTML("beforeend",r):h.innerHTML=r,$.refresh()}function B(t){return t.map(({webformatURL:o,largeImageURL:r,tags:a,likes:e,views:i,comments:l,downloads:v})=>`
        <a class="gallery-item" href="${r}">
          <img src="${o}" alt="${a}" width="360" height="200" />
          <div class="gallery-info">
            <ul class="info-list">
              <li><h3>Likes</h3><p>${e}</p></li>
              <li><h3>Views</h3><p>${i}</p></li>
              <li><h3>Comments</h3><p>${l}</p></li>
              <li><h3>Downloads</h3><p>${v}</p></li>
            </ul>
          </div>
        </a>
      `).join("")}function E(){h.innerHTML=""}function O(){n==null||n.classList.remove("is-hidden")}function p(){n==null||n.classList.add("is-hidden")}function S(){L.classList.remove("is-hidden")}function m(){L.classList.add("is-hidden")}function x(){w.classList.remove("is-hidden")}function H(){w.classList.add("is-hidden")}const g=document.querySelector(".form"),D=document.querySelector(".load");let f="",c=1;const u=15;let d=0;g.addEventListener("submit",async t=>{t.preventDefault();const o=g.elements["search-text"].value.trim();if(!o){s.warning({title:"Warning",message:"Please enter a search term!",position:"topRight",timeout:3e3,color:"orange"});return}f=o,c=1,E(),m(),O();try{const r=await y(f,c,u);if(d=r.totalHits,p(),!r.hits.length){s.error({title:"Sorry",message:"No images found. Please try another query!",position:"topRight",timeout:5e3,color:"red"});return}b(r.hits),s.success({title:"Success",message:`Found ${d} images!`,position:"topRight",timeout:3e3,color:"green"}),d>u&&S()}catch(r){p(),s.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight",timeout:5e3,color:"red"}),console.error("Fetch error:",r)}});D.addEventListener("click",async()=>{c+=1,x(),m();try{const t=await y(f,c,u);b(t.hits,!0),G(),c*u>=d?(s.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:4e3,color:"blue"}),m()):S()}catch(t){s.error({title:"Error",message:"Could not load more images.",position:"topRight",timeout:5e3,color:"red"}),console.error("Load more error:",t)}finally{H()}});function G(){const t=document.querySelector(".gallery a");if(t){const o=t.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
